apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: telegram-advertiser
  name: telegram-advertiser
  namespace: projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-advertiser
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: telegram-advertiser
    spec:
      containers:
        - image: 192.168.4.30:5000/telegram-advertiser:1.0.1
          name: telegram-advertiser
          resources: { }
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-vault
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-vault
                  key: password
            - name: RABBITMQ_URL
              value: rabbitmq.broker:5672
            - name: RABBITMQ_EXCHANGE_NAME
              value: exchange.home.events
            - name: RABBITMQ_QUEUE_NAME
              value: telegramadvertiser.home.events
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-vault
                  key: token
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-vault
                  key: chat-id
status: { }
